# Generated by Django 4.2.16 on 2025-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to='user/profile_pictures/%Y/%m/%d/', verbose_name='avatar'),
        ),
    ]
