# Generated by Django 4.2.16 on 2025-02-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=120)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('single', 'Одиночный выбор ответа'), ('multiple', 'Множественный выбор ответов'), ('input-text', 'Ввод текста')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficult', models.CharField(choices=[('Easy-Quiz', 'Лёгкая'), ('Medium-Quiz', 'Средняя'), ('Hard-Quiz', 'Тяжёлая'), ('Very-hard-Quiz', 'Очень сложная')], default='Easy-Quiz', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('percentage', models.FloatField(help_text='Процент правильных ответов')),
                ('time_taken', models.FloatField(help_text='Время выполнения в секундах')),
                ('completed_at', models.DateTimeField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz_app.quiz')),
            ],
        ),
    ]
