# Generated by Django 4.2.16 on 2025-02-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_answer_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiestion',
            new_name='Question',
        ),
    ]
