# Generated by Django 4.2.16 on 2025-02-20 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0004_rename_quiestion_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizResilt',
            new_name='QuizResult',
        ),
    ]
