# Generated by Django 4.2.16 on 2025-02-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_rename_quizresilt_quizresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='correct_answers',
            field=models.PositiveIntegerField(help_text='Верных ответов'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.PositiveIntegerField(help_text='Количество вопросов'),
        ),
    ]
